package com.example.liquidbasebq.tools;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;

/**
 * A fast, developer-friendly CLI for scaffolding SQL-first Liquibase
 * migrations.
 * Run via: ./mvnw -q -DskipTests exec:java
 * -Dexec.mainClass=com.example.liquidbasebq.tools.ChangeScaffoldCli
 * -Dexec.args="..."
 */
public class ChangeScaffoldCli {

    private static final String CHANGELOG_DIR = "src/main/resources/db/changelog";
    private static final String DDL_DIR = CHANGELOG_DIR + "/sql/ddl";
    private static final String ROLLBACK_DIR = CHANGELOG_DIR + "/sql/rollback";
    private static final String MASTER_XML = CHANGELOG_DIR + "/db.changelog-master.xml";

    public static void main(String[] args) {
        try {
            System.out.println("🚀 Liquibase Change Scaffold Tool");
            System.out.println("────────────────────────────────────────────────");

            Map<String, String> argsMap = parseArgs(args);
            validateArgs(argsMap);

            String name = argsMap.get("--name");
            String domain = argsMap.get("--domain");
            String contexts = argsMap.get("--contexts");
            String labels = argsMap.get("--labels");
            String author = argsMap.getOrDefault("--author", getGitUserEmail());
            boolean registerMaster = argsMap.containsKey("--register-master");

            // Generate Change ID
            String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"));
            String safeName = name.replaceAll("[^a-zA-Z0-9_-]", "-").toLowerCase();
            String changeId = timestamp + "-" + safeName;

            // Define Paths
            Path domainDdlDir = Paths.get(DDL_DIR, domain);
            Path domainRollbackDir = Paths.get(ROLLBACK_DIR, domain);

            Files.createDirectories(domainDdlDir);
            Files.createDirectories(domainRollbackDir);

            File ddlFile = domainDdlDir.resolve(changeId + ".sql").toFile();
            File rollbackFile = domainRollbackDir.resolve(changeId + "_rollback.sql").toFile();
            File xmlFile = Paths.get(CHANGELOG_DIR, changeId + ".xml").toFile();

            // 1. Write Forward SQL
            try (PrintWriter out = new PrintWriter(new FileWriter(ddlFile))) {
                out.println("-- Migration: " + name);
                out.println("-- Auto-generated by ChangeScaffoldCli. Please add your DDL here.");
                out.println();
                out.println("-- E.g. CREATE TABLE `my_table` (id STRING, nested STRUCT<a INT64, b STRING>);");
                out.println();
            }

            // 2. Write Rollback SQL
            try (PrintWriter out = new PrintWriter(new FileWriter(rollbackFile))) {
                out.println("-- Rollback for Migration: " + name);
                out.println("-- Auto-generated by ChangeScaffoldCli. Please add your rollback DDL here.");
                out.println();
                out.println("-- E.g. DROP TABLE IF EXISTS `my_table`;");
                out.println();
            }

            // 3. Write XML Wrapper
            try (PrintWriter out = new PrintWriter(new FileWriter(xmlFile))) {
                out.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                out.println("<databaseChangeLog xmlns=\"http://www.liquibase.org/xml/ns/dbchangelog\"");
                out.println("        xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"");
                out.println("        xsi:schemaLocation=\"http://www.liquibase.org/xml/ns/dbchangelog");
                out.println("        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd\">");
                out.println();
                out.println("    <changeSet id=\"" + changeId + "\" author=\"" + author + "\" context=\"" + contexts
                        + "\" labels=\"" + labels + "\">");
                out.println(
                        "        <!-- ⚠ PRECONDITION: If this is a destructive change, uncomment and define preconditions -->");
                out.println("        <!--");
                out.println("        <preConditions onFail=\"MARK_RAN\">");
                out.println("            <columnExists tableName=\"my_table\" columnName=\"old_column\"/>");
                out.println("        </preConditions>");
                out.println("        -->");
                out.println();
                out.println("        <!-- Forward SQL -->");
                out.println("        <sqlFile path=\"db/changelog/sql/ddl/" + domain + "/" + changeId
                        + ".sql\" splitStatements=\"true\" stripComments=\"true\"/>");
                out.println();
                out.println("        <!-- Reverse SQL -->");
                out.println("        <rollback>");
                out.println("            <sqlFile path=\"db/changelog/sql/rollback/" + domain + "/" + changeId
                        + "_rollback.sql\" splitStatements=\"true\" stripComments=\"true\"/>");
                out.println("        </rollback>");
                out.println("    </changeSet>");
                out.println("</databaseChangeLog>");
            }

            // 4. Register in Master
            if (registerMaster) {
                appendIncludeToMaster(changeId);
            }

            System.out.println();
            System.out.println("✅ Scaffold Complete!");
            System.out.println();
            System.out.println("📁 Created Files:");
            System.out.println("   📝 DDL:      " + ddlFile.getPath());
            System.out.println("   ⏪ Rollback: " + rollbackFile.getPath());
            System.out.println("   🏷️  Wrapper:  " + xmlFile.getPath());
            if (registerMaster) {
                System.out.println("   🔗 Master:   Registered in db.changelog-master.xml");
            }
            System.out.println();
            System.out.println("🚀 Next Steps:");
            System.out.println("   1. Edit the generated DDL and Rollback SQL files.");
            System.out.println("   2. Validate locally:");
            System.out.println(
                    "      ./mvnw -q -DskipTests spring-boot:run -Dspring-boot.run.arguments=\"--action=validate-strict\"");
            System.out.println("   3. Preview deployment changes:");
            System.out.println(
                    "      ./mvnw -q -DskipTests spring-boot:run -Dspring-boot.run.profiles=dev1 -Dspring-boot.run.arguments=\"--action=update-sql\"");
            System.out.println();

        } catch (Exception e) {
            System.err.println("❌ Scaffold Failed: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }

    private static Map<String, String> parseArgs(String[] args) {
        Map<String, String> map = new HashMap<>();
        for (int i = 0; i < args.length; i++) {
            if (args[i].startsWith("--")) {
                if (args[i].equals("--register-master")) {
                    map.put("--register-master", "true");
                } else if (i + 1 < args.length && !args[i + 1].startsWith("--")) {
                    map.put(args[i], args[i + 1]);
                    i++;
                }
            }
        }
        return map;
    }

    private static void validateArgs(Map<String, String> args) {
        String[] required = { "--name", "--domain", "--contexts", "--labels" };
        for (String req : required) {
            if (!args.containsKey(req)) {
                throw new IllegalArgumentException("Missing required argument: " + req + "\n" +
                        "Usage: --name <name> --domain <domain> --contexts <ctx> --labels <labels> [--author <email>] [--register-master]");
            }
        }
    }

    private static String getGitUserEmail() {
        try {
            Process process = new ProcessBuilder("git", "config", "user.email").start();
            process.waitFor();
            if (process.exitValue() == 0) {
                String cmdOutput = new String(process.getInputStream().readAllBytes()).trim();
                if (!cmdOutput.isEmpty())
                    return cmdOutput;
            }
        } catch (Exception ignored) {
        }
        return "developer@example.com";
    }

    private static void appendIncludeToMaster(String changeId) throws Exception {
        Path masterPath = Paths.get(MASTER_XML);
        if (!Files.exists(masterPath)) {
            System.err.println("⚠ WARNING: Master changelog not found at " + MASTER_XML);
            return;
        }

        String content = new String(Files.readAllBytes(masterPath));
        String includeTag = "<include file=\"db/changelog/" + changeId + ".xml\"/>";

        if (content.contains("</databaseChangeLog>")) {
            content = content.replace("</databaseChangeLog>", "    " + includeTag + "\n</databaseChangeLog>");
            Files.write(masterPath, content.getBytes());
        } else {
            System.err.println("⚠ WARNING: Could not find </databaseChangeLog> closing tag in " + MASTER_XML);
        }
    }
}
