# Integration Testing Profile configured to use a dynamic dataset ID via environment variables
spring.datasource.url=jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=${BQ_PROJECT_ID};DefaultDataset=${BQ_DATASET_ID};OAuthType=0;Timeout=1000

# Strict validation active during integration tests
liquibase.strict-validation=true

# Keep logs readable in CI
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.liquibase=INFO
